---
title: "Add old links to the bottom of files"
format:
  html:
    embed-resources: true
---

This program was written by Steve Simon on 2025-08-19 and is placed in the public domain.

## Preliminaries

```{r}
#| label: setup
#| message: false
#| warning: false

library(glue)
library(tidyverse)
```


## Loop

```{r}
#| label: add-extra

add_extra <- function(file_path, file_name) {
	file_name |>
    str_remove("\\.qmd$") |>
    str_remove("\\.Rmd$") |>
    str_remove("\\.md$") -> root_name
	read_lines(glue("{file_path}/{file_name}")) -> file_text
	file_text |>
		str_subset("source: ") |>
		str_remove_all(fixed('\"')) |>
		str_remove("source: ") -> src
	print(src)
	if (length(src) != 1) return()
	i1 <- str_which(file_text, fixed("You can find an [earlier version][sim1]"))
	i2 <- str_which(file_text, "^\\[sim2\\]: ")
	print(i1)
	print(i2)
	if (length(i1) != 1) i1 <- 9999
	if (length(i2) != 1) i2 <- 9999
	if ((i1-i2)==3) file_text <- file_text[-(i1:i2)]
	extra_lines <- c(
	  "",
		"Earlier versions are [here][sim1] and [here][sim2].",
		" ",
	  glue("[sim1]: {src}"),
		glue("[sim2]: http://new.pmean.com/{root_name}/"))
	return(c(file_text, extra_lines))
}
```

```{r}
#| label: loop

file_path <- "../gen5/12"
file_path |>
  list.files() |>
  str_subset("md$") -> file_list

for (file_name in file_list) {
  x <- add_extra(file_path, file_name) 
  # cat(x, sep="\n")
  write_lines(x, file=glue("{file_path}/{file_name}"))
}
```
