---
title: "Count fences in all gen5 files"
format:
  html:
    embed-resources: true
---

This program was written by Steve Simon on 2025-08-19 and is placed in the public domain.

## Preliminaries

```{r}
#| label: setup
#| message: false
#| warning: false

library(glue)
library(tidyverse)
```


## function

```{r}
#| label: function

start_fence <- c(
  div=fixed('<div class="notes">'),
  colons="^::: notes",
  backticks="^```\\{")

end_fence <- c(
  div=fixed('</div>'),
  colons="^:::$",
  backticks="^```$")

count_fences <- function(file_path, file_name, i) {
	read_lines(glue("{file_path}/{file_name}")) -> file_text
  
	file_text |>
		str_subset(start_fence[i]) |>
	  length() -> n1
	
	file_text |>
		str_subset(end_fence[i]) |>
	  length() -> n2
	if (n1 == n2) return(n1*100+n2)
	
	cat("\n")
	cat(glue("{file_path}/{file_name}"))
	return(n1*100+n2)
}
```

```{r}
#| label: loop

yr_list <- c("00", as.character(16:25))
fence <- "backticks"

n_list <- NULL
for (yr in yr_list) {
  file_path <- glue("../gen5/{yr}")
  file_path |>
    list.files() |>
    str_subset("md$") -> file_list

  for (file_name in file_list) {
    count_fences(file_path, file_name, fence) |> append(n_list) -> n_list
  }
}

table(n_list)
```
